### ISSUE TITLE
Errors when running Sentinel-1 change detection using 'sar_seq_s1.sh'

### ISSUE THREAD

**Issue by elfmanryan** [mortcanty/SARDocker#1]
Good morning @mortcanty,
First of all thanks for making your code available.  I am having a little trouble with the sar_seq_s1.sh script and was hoping for some insight, any help would be greatly appreciated. 
I am working with a stack of Sentinel-1 of orbit slices (in this case: relative orbit 68, slice 5). Prep was done in SNAP. Each image has a duel pol C2 matrix (4 bands: C11, C12-real, C12 imag, C22). 
Processing chain went: Orbit Cal-> Calibration->Topsar-Deburst -> Polarimetric matrices -> Multilook -> Terrain-Correction (UTM automatic). 
Your script to estimate the number of looks worked great, and indicated a clear Gaussian peak at ~4.7 which I rounded to 5.
My errors are with the sar_seq_s1.sh. This was my call to the docker script:
`!/home/sar_seq_s1.sh SLC_20161005T091117__prep_r68_s5 SLC_20161017T091117__prep_r68_s5 SLC_20161029T091118__prep_r68_s5 SLC_20161110T091117__prep_r68_s5 [0,0,500,500] 5 0.01`

**Errors:**
I am getting an `ERROR 5: Access window RasterIO out of range error`
and `unsupported operand type(s) for +=: 'NoneType' and 'NoneType'`

I tried several subsets, the printout below was the result for  [0,0,500,500] on a ~17000 x 21000 raster. I do not get the above (access and type) errors if I subset away from the edge e.g. [500,500,1000,1000].  However I really need to run the change detection on the whole image...

The next math error i get regardless : 
``` invalid value encountered in divide ir = abs(ifft2((f0 * f1.conjugate()) / (abs(f0) * abs(f1))))```
I suspected because the noData from the Sentinel-1 chain has defaulted to 0.0 it might be a Div/0 error, so i tried changing it to 0.00001 as a test but got the same result.

Not fatal, but i also always get a fail to find the controller file, I am told this might be a timeout triggered by the above errors:
```
Connection file '~/.ipython/profile_default/security/ipcontroller-client.json' not found.
You have attempted to connect to an IPython Cluster but no Controller could be found.
```

**This is the process printout:**
```
***** Multitemporal PolSAR Change Detection **********
***** Sentenel-1 dualpol imagery *********************
******************************************************
number of images  4
ENL               5
spatial subset    [0,0,500,500]
===========================
Spatial/spectral subsetting
===========================
Mon Sep 18 09:28:33 2017
Input /home/imagery/SLC_20161005T091117__prep_r68_s5.tif
elapsed time: 1.0587720871
 
attempting parallel execution of co-registration ...
Waiting for connection file: ~/.ipython/profile_default/security/ipcontroller-client.json
Connection file '~/.ipython/profile_default/security/ipcontroller-client.json' not found.
You have attempted to connect to an IPython Cluster but no Controller could be found.
Please double-check your configuration and ensure that a cluster is running. 
Failed, so running sequential co-registration ...
=========================
     Register SAR
=========================
Mon Sep 18 09:29:04 2017
Reference SAR image:
 /home/imagery/SLC_20161005T091117__prep_r68_s5.tif
Target SAR image:
 /home/imagery/SLC_20161017T091117__prep_r68_s5.tif
ERROR 5: /home/imagery/SLC_20161017T091117__prep_r68_s5.tif, band 1: Access window out of range in RasterIO().  Requested
(-3,-3) of size 500x500 on raster of 21276x17424.
warping 4 bands (dual pol)...
ERROR 5: /home/imagery/SLC_20161017T091117__prep_r68_s5.tif, band 4: Access window out of range in RasterIO().  Requested
(-3,-3) of size 500x500 on raster of 21276x17424.
registersar failed: unsupported operand type(s) for +=: 'NoneType' and 'NoneType'
=========================
     Register SAR
=========================
Mon Sep 18 09:29:04 2017
Reference SAR image:
 /home/imagery/SLC_20161005T091117__prep_r68_s5.tif
Target SAR image:
 /home/imagery/SLC_20161029T091118__prep_r68_s5.tif
ERROR 5: /home/imagery/SLC_20161029T091118__prep_r68_s5.tif, band 1: Access window out of range in RasterIO().  Requested
(2,-3) of size 500x500 on raster of 21276x17424.
warping 4 bands (dual pol)...
ERROR 5: /home/imagery/SLC_20161029T091118__prep_r68_s5.tif, band 4: Access window out of range in RasterIO().  Requested
(2,-3) of size 500x500 on raster of 21276x17424.
registersar failed: unsupported operand type(s) for +=: 'NoneType' and 'NoneType'
=========================
     Register SAR
=========================
Mon Sep 18 09:29:05 2017
Reference SAR image:
 /home/imagery/SLC_20161005T091117__prep_r68_s5.tif
Target SAR image:
 /home/imagery/SLC_20161110T091117__prep_r68_s5.tif
warping 4 bands (dual pol)...
/usr/local/lib/python2.7/dist-packages/auxil/auxil.py:735: RuntimeWarning: invalid value encountered in divide
  ir = abs(ifft2((f0 * f1.conjugate()) / (abs(f0) * abs(f1))))
registersar failed: 
elapsed time for co-registration: 32.9703288078
===============================================
     Multi-temporal SAR Change Detection
===============================================
Mon Sep 18 09:29:06 2017
First (reference) filename:  /home/imagery/SLC_20161005T091117__prep_r68_s5_sub.tif
number of images: 4
equivalent number of looks: 5.000000
significance level: 0.010000
pre-calculating Rj and p-values ...
attempting parallel calculation ...
Waiting for connection file: ~/.ipython/profile_default/security/ipcontroller-client.json
Connection file '~/.ipython/profile_default/security/ipcontroller-client.json' not found.
You have attempted to connect to an IPython Cluster but no Controller could be found.
Please double-check your configuration and ensure that a cluster is running. 
failed, so running sequential calculation ...
ell=  1 Error: not a string  -- Could not read file
```

**Comment by elfmanryan** [comment]
I have setup outside the docker, and put in some print statements where its failing on auxil.py, line: 735.
rewriting:
`ir = abs(ifft2((f0 * f1.conjugate()) / (abs(f0) * abs(f1))))`

as: 
```
 nominator = f0 * f1.conjugate()
 denominator = abs(f0) * abs(f1)
 result = nominator / denominator
```

i get:
``` nominator =
 [[  4.77170843e+13+0.j   0.00000000e+00+0.j   0.00000000e+00+0.j ...,
    0.00000000e+00+0.j   0.00000000e+00+0.j   0.00000000e+00+0.j]
 [  0.00000000e+00+0.j   0.00000000e+00+0.j   0.00000000e+00+0.j ...,
    0.00000000e+00+0.j   0.00000000e+00+0.j   0.00000000e+00+0.j]
 [  0.00000000e+00+0.j   0.00000000e+00+0.j   0.00000000e+00+0.j ...,
    0.00000000e+00+0.j   0.00000000e+00+0.j   0.00000000e+00+0.j]

 ...,
 [  0.00000000e+00+0.j   0.00000000e+00+0.j   0.00000000e+00+0.j ...,
    0.00000000e+00+0.j   0.00000000e+00+0.j   0.00000000e+00+0.j]
 [  0.00000000e+00+0.j   0.00000000e+00+0.j   0.00000000e+00+0.j ...,
    0.00000000e+00+0.j   0.00000000e+00+0.j   0.00000000e+00+0.j]
 [  0.00000000e+00+0.j   0.00000000e+00+0.j   0.00000000e+00+0.j ...,
    0.00000000e+00+0.j   0.00000000e+00+0.j   0.00000000e+00+0.j]]

denominator = 
[[  4.77170843e+13   0.00000000e+00   0.00000000e+00 ...,   0.00000000e+00
    0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00 ...,   0.00000000e+00
    0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00 ...,   0.00000000e+00
    0.00000000e+00   0.00000000e+00]
 ...,
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00 ...,   0.00000000e+00
    0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00 ...,   0.00000000e+00
    0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00 ...,   0.00000000e+00
    0.00000000e+00   0.00000000e+00]]
```

**Comment by mortcanty** [comment]
Hi

I am on vacation till the week end. Will get back to you then. Can you send
me a test dataset?

Best regards

Mort

Am 18.09.2017 13:17 schrieb "elfmanryan" <notifications@github.com>:

Good morning @mortcanty <https://github.com/mortcanty>,
First of all thanks for making your code available. I am having a little
trouble with the sar_seq_s1.sh script and was hoping for some insight, any
help would be greatly appreciated.
I am working with a stack of Sentinel-1 of orbit slices (in this case:
relative orbit 68, slice 5). Prep was done in SNAP. Each image has a duel
pol C2 matrix (4 bands: C11, C12-real, C12 imag, C22).
Processing chain went: Orbit Cal-> Calibration->Topsar-Deburst ->
Polarimetric matrices -> Multilook -> Terrain-Correction (UTM automatic).
Your script to estimate the number of looks worked great, and indicated a
clear Gaussian peak at ~4.7 which I rounded to 5.
My errors are with the sar_seq_s1.sh. This was my call to the docker script:
!/home/sar_seq_s1.sh SLC_20161005T091117__prep_r68_s5
SLC_20161017T091117__prep_r68_s5 SLC_20161029T091118__prep_r68_s5
SLC_20161110T091117__prep_r68_s5 [0,0,500,500] 5 0.01

*Errors:*
I am getting an ERROR 5: Access window RasterIO out of range error
and unsupported operand type(s) for +=: 'NoneType' and 'NoneType'

I tried several subsets, the printout below was the result for
[0,0,500,500] on a ~17000 x 21000 raster. I do not get the above (access
and type) errors if I subset away from the edge e.g. [500,500,100,100].
However I really need to run the change detection on the whole image...

The next math error i get regardless :
invalid value encountered in divide ir = abs(ifft2((f0 * f1.conjugate()) /
(abs(f0) * abs(f1))))
I suspected because the noData from the Sentinel-1 chain has defaulted to
0.0 it might be a Div/0 error, so i tried changing it to 0.00001 as a test
but got the same result.

Not fatal, but i also always get a fail to find the controller file, I am
told this might be a timeout triggered by the above errors:

Connection file
'~/.ipython/profile_default/security/ipcontroller-client.json' not
found.
You have attempted to connect to an IPython Cluster but no Controller
could be found.

*This is the process printout:*

***** Multitemporal PolSAR Change Detection **********
***** Sentenel-1 dualpol imagery *********************
******************************************************
number of images  4
ENL               5
spatial subset    [0,0,500,500]
===========================
Spatial/spectral subsetting
===========================
Mon Sep 18 09:28:33 2017
Input /home/imagery/SLC_20161005T091117__prep_r68_s5.tif
elapsed time: 1.0587720871

attempting parallel execution of co-registration ...
Waiting for connection file:
~/.ipython/profile_default/security/ipcontroller-client.json
Connection file
'~/.ipython/profile_default/security/ipcontroller-client.json' not
found.
You have attempted to connect to an IPython Cluster but no Controller
could be found.
Please double-check your configuration and ensure that a cluster is running.
Failed, so running sequential co-registration ...
=========================
     Register SAR
=========================
Mon Sep 18 09:29:04 2017
Reference SAR image:
 /home/imagery/SLC_20161005T091117__prep_r68_s5.tif
Target SAR image:
 /home/imagery/SLC_20161017T091117__prep_r68_s5.tif
ERROR 5: /home/imagery/SLC_20161017T091117__prep_r68_s5.tif, band 1:
Access window out of range in RasterIO().  Requested
(-3,-3) of size 500x500 on raster of 21276x17424.
warping 4 bands (dual pol)...
ERROR 5: /home/imagery/SLC_20161017T091117__prep_r68_s5.tif, band 4:
Access window out of range in RasterIO().  Requested
(-3,-3) of size 500x500 on raster of 21276x17424.
registersar failed: unsupported operand type(s) for +=: 'NoneType' and
'NoneType'
=========================
     Register SAR
=========================
Mon Sep 18 09:29:04 2017
Reference SAR image:
 /home/imagery/SLC_20161005T091117__prep_r68_s5.tif
Target SAR image:
 /home/imagery/SLC_20161029T091118__prep_r68_s5.tif
ERROR 5: /home/imagery/SLC_20161029T091118__prep_r68_s5.tif, band 1:
Access window out of range in RasterIO().  Requested
(2,-3) of size 500x500 on raster of 21276x17424.
warping 4 bands (dual pol)...
ERROR 5: /home/imagery/SLC_20161029T091118__prep_r68_s5.tif, band 4:
Access window out of range in RasterIO().  Requested
(2,-3) of size 500x500 on raster of 21276x17424.
registersar failed: unsupported operand type(s) for +=: 'NoneType' and
'NoneType'
=========================
     Register SAR
=========================
Mon Sep 18 09:29:05 2017
Reference SAR image:
 /home/imagery/SLC_20161005T091117__prep_r68_s5.tif
Target SAR image:
 /home/imagery/SLC_20161110T091117__prep_r68_s5.tif
warping 4 bands (dual pol)...
/usr/local/lib/python2.7/dist-packages/auxil/auxil.py:735:
RuntimeWarning: invalid value encountered in divide
  ir = abs(ifft2((f0 * f1.conjugate()) / (abs(f0) * abs(f1))))
registersar failed:
elapsed time for co-registration: 32.9703288078
===============================================
     Multi-temporal SAR Change Detection
===============================================
Mon Sep 18 09:29:06 2017
First (reference) filename:
/home/imagery/SLC_20161005T091117__prep_r68_s5_sub.tif
number of images: 4
equivalent number of looks: 5.000000
significance level: 0.010000
pre-calculating Rj and p-values ...
attempting parallel calculation ...
Waiting for connection file:
~/.ipython/profile_default/security/ipcontroller-client.json
Connection file
'~/.ipython/profile_default/security/ipcontroller-client.json' not
found.
You have attempted to connect to an IPython Cluster but no Controller
could be found.
Please double-check your configuration and ensure that a cluster is running.
failed, so running sequential calculation ...
ell=  1 Error: not a string  -- Could not read file

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/mortcanty/SARDocker/issues/1>, or mute the thread

**Comment by elfmanryan** [comment]
Thanks for the quick reply,  I will create a s3 bucket with the full test images, and also some subset images. 
I have successfully called the omnibus.py outside the docker on a preclipped subsets, one fully inside the data extent, and one overlapping the nodata edge. I am now in the process of working backwards, next looking at the sar_seq.py. 
Will post any developments, and thanks again for your help.
Ryan

**Comment by elfmanryan** [comment]
Iv added some links below to a sample dataset (4 prepped tifs of s1, in time series for relative orbit 68, slice 5). 

Update on testing: its apparent to me that the initial subset/registration fails if the image is larger than the subset dims. If i make a clip of the stack (below) and pass the clipped dimensions, the registration works fine and so does the sequential change  detection.

Although I still cant get the parrallel processing to  work which would be very nifty.

I  have approx 19 slices per stack. As a stress test, we loaded the full 19 image stack of whole slices to AWS and it quickly gobbles 60GB+ memory and then crashes silently. A more robust approach i am aiming for now is to use  `gdal_retile.py `to make clipped substacks and` gdal_mosaic.py` to recombine the resulting change maps. Currently still testing this today.

Full images:
http://sar-test-data.s3.amazonaws.com/full_image_stack/SLC_20161005T091117__prep_r68_s5.tif
http://sar-test-data.s3.amazonaws.com/full_image_stack/SLC_20161017T091117__prep_r68_s5.tif
http://sar-test-data.s3.amazonaws.com/full_image_stack/SLC_20161029T091118__prep_r68_s5.tif
http://sar-test-data.s3.amazonaws.com/full_image_stack/SLC_20161110T091117__prep_r68_s5.tif

clips: 
http://sar-test-data.s3.amazonaws.com/clip/SLC_20161005T091117__prep_r68_s5.tif
http://sar-test-data.s3.amazonaws.com/clip/SLC_20161017T091117__prep_r68_s5.tif
http://sar-test-data.s3.amazonaws.com/clip/SLC_20161029T091118__prep_r68_s5.tif
http://sar-test-data.s3.amazonaws.com/clip/SLC_20161110T091117__prep_r68_s5.tif

**Comment by elfmanryan** [comment]
@mortcanty  The change detection itself works excellent. Thank you. Just to say overcame the above subsetting issues by tiling the image stacks and then sequentially operating on them as substacks before reassembling the results. 'Chunking' in this way also helped with memory load-hope this helps anyone following, I shall close the issue.
